import { describe, expect, test } from 'bun:test';
import { planEcommerceSuiteTool } from './ecommerce-suite.tools';
import { generateImageTool, getAutoGeneratedImageSize } from './generation.tools';
import {
  getGenerationAspectRatio,
  getGptImageGenerationSize,
} from '../ecommerce-plan';

function createContext(canvasState: any[] = []) {
  const events: any[] = [];
  const imageRequests: any[] = [];
  let plan: any = null;
  let sequence = 0;
  const ctx = {
    sessionId: 'test-session',
    assets: [{
      id: 'asset_product',
      url: 'data:image/png;base64,AA==',
      name: 'product.png',
      createdAt: Date.now(),
    }],
    canvasState,
    origin: 'http://localhost:3000',
    newRefId: (prefix = 'node') => `${prefix}_${++sequence}`,
    sink: {
      emit: (event: any) => events.push(event),
      canvas: (op: any) => events.push({ type: 'canvas_op', op }),
    },
    memory: {
      getPlan: () => plan,
      setPlan: (_sessionId: string, nextPlan: any) => { plan = nextPlan; },
    },
    ai: {
      generateImageFromJson: async (request: any) => {
        imageRequests.push(request);
        return { taskId: `task_${imageRequests.length}`, status: 'generating' };
      },
    },
  } as any;
  return { ctx, events, imageRequests };
}

describe('generateImageTool ecommerce placement', () => {
  test('recovers omitted metadata and creates a root-canvas image grid', async () => {
    const { ctx, events, imageRequests } = createContext();
    const planResult = await planEcommerceSuiteTool.execute({
      platforms: ['amazon'],
      sourceAssetId: 'asset_product',
      imagesPerPlatform: 3,
    }, ctx);
    const deliverables = (planResult.output as any).deliverables;

    await Promise.all(deliverables.map((item: any) =>
      generateImageTool.execute({
        prompt: `Generate ${item.role}`,
      }, ctx),
    ));

    const imageNodes = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .filter((node) => node.type === 'image_gen');
    expect(imageNodes.every((node) => node.parentId === undefined)).toBe(true);
    expect(imageNodes.map((node) => ({
      x: node.x,
      y: node.y,
      width: node.width,
      height: node.height,
      aspectRatio: node.aspectRatio,
      preserveLayout: node.preserveLayout,
    }))).toEqual(deliverables.map((item: any) => ({
      x: item.x,
      y: item.y,
      width: item.width,
      height: item.height,
      aspectRatio: '1:1',
      preserveLayout: true,
    })));
    expect(imageRequests.map((request) => request.aspectRatio)).toEqual([
      '1:1',
      '1:1',
      '1:1',
    ]);
    expect(imageRequests.every((request) => request.size === '2000x2000')).toBe(true);
    expect(imageRequests.every((request) => request.quality === 'high')).toBe(true);
    expect(imageRequests.every((request) => request.images?.[0] === 'data:image/png;base64,AA==')).toBe(true);
    expect(imageRequests.map((request) => request.prompt)).toEqual(
      deliverables.map((item: any) => `Generate ${item.role}`),
    );
    expect(events.some((event) => event.type === 'canvas_op' && event.op.node?.type === 'frame')).toBe(false);
  });

  test('chooses a provider-supported ratio closest to the target frame', () => {
    expect(getGenerationAspectRatio(2000, 2000)).toBe('1:1');
    expect(getGenerationAspectRatio(750, 1000)).toBe('3:4');
    expect(getGenerationAspectRatio(1464, 600)).toBe('21:9');
    expect(getGptImageGenerationSize(2000, 2000)).toBe('2000x2000');
    expect(getGptImageGenerationSize(1464, 600)).toBe('1472x608');
  });

  test('ignores a stale parent frame and places the suite below it', async () => {
    const legacyFrames = [{
      refId: 'legacy_frame',
      type: 'frame',
      width: 2000,
      height: 2000,
      x: 0,
      y: 0,
    }];
    const { ctx, events } = createContext(legacyFrames);
    await planEcommerceSuiteTool.execute({
      platforms: ['amazon'],
      sourceAssetId: 'asset_product',
      imagesPerPlatform: 1,
    }, ctx);

    await generateImageTool.execute({
      prompt: 'Regenerate main image',
      parentId: 'legacy_frame',
    }, ctx);
    const generatedNode = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .find((node) => node.type === 'image_gen');
    expect(generatedNode.parentId).toBeUndefined();
    expect(generatedNode.x).toBe(0);
    expect(generatedNode.y).toBe(2240);
  });

  test('rejects an image parent before starting paid generation', async () => {
    const { ctx, events, imageRequests } = createContext([
      { refId: 'product_image', type: 'image', url: '/files/product.png' },
    ]);

    await expect(generateImageTool.execute({
      prompt: 'Add a headline',
      parentId: 'product_image',
    }, ctx)).rejects.toThrow('not a frame or group');

    expect(imageRequests).toHaveLength(0);
    expect(events).toHaveLength(0);
  });

  test('uses the prepared ecommerce source instead of the low-resolution original', async () => {
    const prepared = 'data:image/png;base64,UFJFUEFSRUQ=';
    const { ctx, imageRequests } = createContext([
      {
        refId: 'upscale_product',
        type: 'image',
        url: prepared,
        width: 1200,
        height: 1200,
      },
    ]);
    Object.assign(ctx.assets[0], { width: 224, height: 224 });
    await planEcommerceSuiteTool.execute({
      platforms: ['taobao'],
      sourceAssetId: 'asset_product',
      productName: '城市跑鞋',
      sellingPoints: ['用户明确提供的透气鞋面'],
      imagesPerPlatform: 2,
    }, ctx);
    const plan = ctx.memory.getPlan();
    plan.preferredSourceRefId = 'upscale_product';
    plan.steps[0].status = 'completed';

    await generateImageTool.execute({ prompt: 'Create the hero' }, ctx);
    await generateImageTool.execute({ prompt: 'Create the benefit visual' }, ctx);

    expect(imageRequests.every((request) => request.images?.[0] === 'data:image/png;base64,AA==')).toBe(true);
    expect(imageRequests.every((request) => request.images?.[1] === prepared)).toBe(true);
    expect(imageRequests.map((request) => request.prompt)).toEqual([
      'Create the hero',
      'Create the benefit visual',
    ]);
  });

  test('blocks paid ecommerce generation until required source preparation completes', async () => {
    const { ctx, imageRequests } = createContext();
    Object.assign(ctx.assets[0], { width: 224, height: 224 });
    await planEcommerceSuiteTool.execute({
      platforms: ['taobao'],
      sourceAssetId: 'asset_product',
      imagesPerPlatform: 1,
    }, ctx);

    await expect(generateImageTool.execute({ prompt: 'Generate the main image' }, ctx))
      .rejects.toThrow('Complete upscale_image');
    expect(imageRequests).toHaveLength(0);
  });

  test('uses the agent-authored prompt and ignores a stale plan for a direct image request', async () => {
    const { ctx, events, imageRequests } = createContext();
    Object.assign(ctx.assets[0], { width: 224, height: 224 });
    await planEcommerceSuiteTool.execute({
      platforms: ['taobao'],
      sourceAssetId: 'asset_product',
      imagesPerPlatform: 2,
    }, ctx);

    ctx.directImageRequest = true;
    ctx.userInput = '帮我生成这双鞋的淘宝详情页';
    ctx.defaultImageReferenceIds = ['asset_product'];
    const agentPrompt = 'Create a concise Taobao detail page based on the referenced shoe.';
    await generateImageTool.execute({
      prompt: agentPrompt,
      style: 'clean ecommerce',
      aspectRatio: '2:3',
      size: '1024x1536',
    }, ctx);

    expect(imageRequests).toHaveLength(1);
    expect(imageRequests[0]).toMatchObject({
      prompt: agentPrompt,
      images: ['data:image/png;base64,AA=='],
      style: 'clean ecommerce',
      aspectRatio: '2:3',
      size: '1024x1536',
    });
    const generatedNode = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .find((node) => node.type === 'image_gen');
    expect(generatedNode.prompt).toBe(agentPrompt);
    expect(generatedNode.platform).toBeUndefined();
    expect(generatedNode.deliverable).toBeUndefined();
  });

  test('respects the agent decision to opt out of an implicit reference', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.defaultImageReferenceIds = ['asset_product'];

    await generateImageTool.execute({
      prompt: 'Generate an unrelated abstract image.',
      refImages: [],
    }, ctx);

    expect(imageRequests[0].prompt).toBe('Generate an unrelated abstract image.');
    expect(imageRequests[0].images).toEqual([]);
  });

  test('arranges direct image generations in call order with stable display sizes', async () => {
    const { ctx, events } = createContext();
    ctx.directImageRequest = true;

    await generateImageTool.execute({ prompt: 'Square', aspectRatio: '1:1' }, ctx);
    await generateImageTool.execute({ prompt: 'Portrait', aspectRatio: '2:3' }, ctx);
    await generateImageTool.execute({ prompt: 'Landscape', size: '1600x900' }, ctx);
    await generateImageTool.execute({ prompt: 'Next row', aspectRatio: '3:4' }, ctx);

    const imageNodes = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .filter((node) => node.type === 'image_gen');
    expect(imageNodes.map((node) => ({
      prompt: node.prompt,
      x: node.x,
      y: node.y,
      width: node.width,
      height: node.height,
      preserveLayout: node.preserveLayout,
    }))).toEqual([
      { prompt: 'Square', x: 0, y: 0, width: 480, height: 480, preserveLayout: true },
      { prompt: 'Portrait', x: 528, y: 0, width: 320, height: 480, preserveLayout: true },
      { prompt: 'Landscape', x: 896, y: 0, width: 480, height: 270, preserveLayout: true },
      { prompt: 'Next row', x: 0, y: 528, width: 360, height: 480, preserveLayout: true },
    ]);
  });

  test('preserves explicit root coordinates without consuming an auto-layout slot', async () => {
    const { ctx, events } = createContext();
    ctx.directImageRequest = true;

    await generateImageTool.execute({
      prompt: 'Pinned image',
      x: 120,
      y: 240,
      width: 300,
      height: 200,
    }, ctx);
    await generateImageTool.execute({ prompt: 'Auto image', aspectRatio: '1:1' }, ctx);

    const imageNodes = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .filter((node) => node.type === 'image_gen');
    expect(imageNodes[0]).toMatchObject({ x: 120, y: 240, width: 300, height: 200 });
    expect(imageNodes[1]).toMatchObject({ x: 120, y: 560, width: 480, height: 480 });
  });

  test('keeps generated images parent-relative inside a frame', async () => {
    const { ctx, events } = createContext([{
      refId: 'frame_1',
      type: 'frame',
      x: 800,
      y: 600,
      width: 720,
      height: 480,
    }]);
    ctx.directImageRequest = true;

    await generateImageTool.execute({
      prompt: 'Frame artwork',
      parentId: 'frame_1',
    }, ctx);

    const imageNode = events
      .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
      .map((event) => event.op.node)
      .find((node) => node.type === 'image_gen');
    expect(imageNode).toMatchObject({
      parentId: 'frame_1',
      x: 0,
      y: 0,
      width: 720,
      height: 480,
      preserveLayout: true,
    });
  });

  test('derives bounded display sizes without changing provider intent', () => {
    expect(getAutoGeneratedImageSize({ aspectRatio: '16:9' })).toEqual({
      width: 480,
      height: 270,
    });
    expect(getAutoGeneratedImageSize({ size: '1024x1536' })).toEqual({
      width: 320,
      height: 480,
    });
    expect(getAutoGeneratedImageSize({ width: 360, aspectRatio: '3:2' })).toEqual({
      width: 360,
      height: 240,
    });
  });
});
