import { describe, expect, test } from 'bun:test';
import {
  generateImageTool,
  getAutoGeneratedImageSize,
  getGenerationAspectRatio,
} from './generation.tools';

function createContext(canvasState: any[] = []) {
  const events: any[] = [];
  const imageRequests: any[] = [];
  let sequence = 0;
  const ctx = {
    sessionId: 'test-session',
    assets: [{
      id: 'asset_product',
      url: 'data:image/png;base64,AA==',
      name: 'product.png',
      createdAt: Date.now(),
    }],
    canvasState,
    origin: 'http://localhost:3000',
    newRefId: (prefix = 'node') => `${prefix}_${++sequence}`,
    sink: {
      emit: (event: any) => events.push(event),
      canvas: (op: any) => events.push({ type: 'canvas_op', op }),
    },
    memory: { getPlan: () => null },
    ai: {
      generateImageFromJson: async (request: any) => {
        imageRequests.push(request);
        return { taskId: `task_${imageRequests.length}`, status: 'generating' };
      },
    },
  } as any;
  return { ctx, events, imageRequests };
}

function generatedNodes(events: any[]): any[] {
  return events
    .filter((event) => event.type === 'canvas_op' && event.op.op === 'add_node')
    .map((event) => event.op.node)
    .filter((node) => node.type === 'image_gen');
}

describe('generateImageTool prompt policy', () => {
  test('passes a full agent-authored prompt through when prompt optimization is explicit', async () => {
    const { ctx, events, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '请优化提示词：帮我生成适合的电商主图，生成 5 张，风格要统一';
    ctx.defaultImageReferenceIds = ['asset_product'];
    const optimizedPrompt =
      '白色厚底运动鞋品牌 campaign 主视觉，夸张低机位透视、深靛蓝空间光场、电光青边缘光与动态切片排版；保持参考鞋款结构与配色，不虚构参数。';

    await generateImageTool.execute({
      prompt: optimizedPrompt,
      platform: 'taobao',
      deliverable: 'main',
      style: 'commercial product photography',
      size: '1024x1024',
      quality: 'hd',
      aspectRatio: '1:1',
    }, ctx);

    expect(imageRequests).toEqual([{
      prompt: optimizedPrompt,
      model: undefined,
      style: 'commercial product photography',
      size: '1024x1024',
      aspectRatio: '1:1',
      quality: 'hd',
      images: ['data:image/png;base64,AA=='],
    }]);
    expect(generatedNodes(events)[0]).toMatchObject({
      prompt: optimizedPrompt,
      preserveLayout: false,
    });
    expect(generatedNodes(events)[0].platform).toBe('taobao');
    expect(generatedNodes(events)[0].deliverable).toBe('main');
  });

  test('keeps only user-authored provider controls for an ordinary request', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '生成 1024x1536、2:3、high 的竖版插画';

    await generateImageTool.execute({
      prompt: 'rewritten prompt',
      size: '1024x1536',
      quality: 'high',
      aspectRatio: '2:3',
      style: 'invented style suffix',
    }, ctx);

    expect(imageRequests[0]).toMatchObject({
      prompt: ctx.userInput,
      size: '1024x1536',
      quality: 'high',
      aspectRatio: '2:3',
    });
    expect(imageRequests[0].style).toBeUndefined();
  });

  test('drops useful-looking rendering notes that the user did not write', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '黑色背景、蓝色霓虹侧光，产品居中，不要文字，写实商业摄影';

    await generateImageTool.execute({
      prompt: 'Use controlled specular highlights and a clean centered silhouette.',
      aspectRatio: '1:1',
    }, ctx);

    expect(imageRequests[0].prompt).toBe(ctx.userInput);
    expect(imageRequests[0].prompt).not.toContain('controlled specular highlights');
    expect(imageRequests[0].quality).toBe('high');
  });

  test('sends the bare A+ task without its request wrapper or agent additions', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '帮我生成这个产品的A+详情页';
    ctx.defaultImageReferenceIds = ['asset_product'];

    await generateImageTool.execute({
      prompt: '专业亚马逊A+长页，包含主视觉、材质、功能和场景模块',
      size: '1024x3072',
      aspectRatio: '1:3',
      style: 'premium ecommerce',
    }, ctx);

    expect(imageRequests[0]).toMatchObject({
      prompt: '生成这个产品的A+详情页',
      images: ['data:image/png;base64,AA=='],
      quality: 'high',
    });
    expect(imageRequests[0].size).toBeUndefined();
    expect(imageRequests[0].aspectRatio).toBeUndefined();
    expect(imageRequests[0].style).toBeUndefined();
  });

  test('sends inferred Amazon suite deliverables as two minimal provider prompts', async () => {
    const { ctx, events, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '帮我生成这个产品的亚马逊套图';
    ctx.defaultImageReferenceIds = ['asset_product'];

    await generateImageTool.execute({
      prompt: '一段会被服务器忽略的专业主图描述',
      platform: 'amazon',
      deliverable: 'main',
      userConstraints: ['电影级灯光'],
      style: 'invented catalog style',
    }, ctx);
    await generateImageTool.execute({
      prompt: '一段会被服务器忽略的专业A+描述',
      platform: 'amazon',
      deliverable: 'a_plus',
      aspectRatio: '1:3',
    }, ctx);

    expect(imageRequests.map((request) => request.prompt)).toEqual([
      '生成主图',
      '生成亚马逊A+详情页',
    ]);
    expect(imageRequests.every((request) =>
      request.style === undefined &&
      request.aspectRatio === undefined &&
      request.images?.[0] === 'data:image/png;base64,AA=='
    )).toBe(true);
    expect(generatedNodes(events).map((node) => node.deliverable)).toEqual([
      'main',
      'a_plus',
    ]);
  });

  test('rejects an invalid suite deliverable before paid generation', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = '生成Shopee套图';

    await expect(generateImageTool.execute({
      prompt: '生成Shopee套图',
      platform: 'shopee',
      deliverable: '专业高端视觉，使用电影级灯光',
    }, ctx)).rejects.toThrow('short structured deliverable name');

    expect(imageRequests).toHaveLength(0);
  });

  test('respects an explicit opt-out from an implicit reference', async () => {
    const { ctx, imageRequests } = createContext();
    ctx.directImageRequest = true;
    ctx.userInput = 'Generate an unrelated abstract image.';
    ctx.defaultImageReferenceIds = ['asset_product'];

    await generateImageTool.execute({
      prompt: 'Generate an unrelated abstract image.',
      refImages: [],
    }, ctx);

    expect(imageRequests[0].prompt).toBe(ctx.userInput);
    expect(imageRequests[0].images).toEqual([]);
  });
});

describe('generateImageTool canvas placement', () => {
  test('rejects an image node as a parent before starting paid generation', async () => {
    const { ctx, events, imageRequests } = createContext([
      { refId: 'product_image', type: 'image', url: '/files/product.png' },
    ]);

    await expect(generateImageTool.execute({
      prompt: 'Add a headline',
      parentId: 'product_image',
    }, ctx)).rejects.toThrow('not a frame or group');

    expect(imageRequests).toHaveLength(0);
    expect(events).toHaveLength(0);
  });

  test('arranges root generations in call order without locking display size', async () => {
    const { ctx, events } = createContext();

    await generateImageTool.execute({ prompt: 'Square', aspectRatio: '1:1' }, ctx);
    await generateImageTool.execute({ prompt: 'Portrait', aspectRatio: '2:3' }, ctx);
    await generateImageTool.execute({ prompt: 'Landscape', size: '1600x900' }, ctx);
    await generateImageTool.execute({ prompt: 'Next row', aspectRatio: '3:4' }, ctx);

    expect(generatedNodes(events).map((node) => ({
      prompt: node.prompt,
      x: node.x,
      y: node.y,
      width: node.width,
      height: node.height,
      preserveLayout: node.preserveLayout,
    }))).toEqual([
      { prompt: 'Square', x: 0, y: 0, width: 1024, height: 1024, preserveLayout: false },
      { prompt: 'Portrait', x: 1072, y: 0, width: 683, height: 1024, preserveLayout: false },
      { prompt: 'Landscape', x: 0, y: 1072, width: 1600, height: 900, preserveLayout: false },
      { prompt: 'Next row', x: 1648, y: 1072, width: 768, height: 1024, preserveLayout: false },
    ]);
  });

  test('preserves explicit root coordinates without consuming an auto-layout slot', async () => {
    const { ctx, events } = createContext();

    await generateImageTool.execute({
      prompt: 'Pinned image',
      x: 120,
      y: 240,
      width: 300,
      height: 200,
    }, ctx);
    await generateImageTool.execute({ prompt: 'Auto image', aspectRatio: '1:1' }, ctx);

    expect(generatedNodes(events)[0]).toMatchObject({ x: 120, y: 240, width: 300, height: 200 });
    expect(generatedNodes(events)[1]).toMatchObject({
      x: 120,
      y: 560,
      width: 1024,
      height: 1024,
      preserveLayout: false,
    });
  });

  test('keeps generated images parent-relative inside a frame', async () => {
    const { ctx, events } = createContext([{
      refId: 'frame_1',
      type: 'frame',
      x: 800,
      y: 600,
      width: 720,
      height: 480,
    }]);

    await generateImageTool.execute({ prompt: 'Frame artwork', parentId: 'frame_1' }, ctx);

    expect(generatedNodes(events)[0]).toMatchObject({
      parentId: 'frame_1',
      x: 0,
      y: 0,
      width: 720,
      height: 480,
      preserveLayout: true,
    });
  });

  test('derives placement estimates and provider ratios for supporting assets', () => {
    expect(getGenerationAspectRatio(2000, 2000)).toBe('1:1');
    expect(getGenerationAspectRatio(750, 1000)).toBe('3:4');
    expect(getGenerationAspectRatio(1464, 600)).toBe('21:9');
    expect(getAutoGeneratedImageSize({ aspectRatio: '16:9' })).toEqual({
      width: 1024,
      height: 576,
    });
    expect(getAutoGeneratedImageSize({ size: '1024x1536' })).toEqual({
      width: 1024,
      height: 1536,
    });
    expect(getAutoGeneratedImageSize({ width: 360, aspectRatio: '3:2' })).toEqual({
      width: 360,
      height: 240,
    });
  });
});
