import type { AgentTool, ToolContext, ToolResult } from '../tool.interface';
import { startBilledAgentTask } from '../../billing/billing-task';
import {
  getCanvasNodeMap,
  reserveRootGridPlacement,
  resolveCanvasContainerParentId,
  resolveNewCanvasRefId,
  upsertCanvasNode,
} from '../canvas-state';
import {
  assertPlannedEcommerceSourceReady,
  buildEcommerceImagePrompt,
  getGenerationAspectRatio,
  getGptImageGenerationSize,
  reservePlannedEcommercePlacement,
} from '../ecommerce-plan';
import { resolveReferencesToBase64 } from './image-reference';

/**
 * Grid reservation / placeholder estimate only.
 * Final canvas display uses natural image pixels unless preserveLayout is set
 * (ecommerce planned slots or images constrained to a parent frame).
 */
const AUTO_LAYOUT_MAX_EDGE = 1024;

function positiveNumber(value: unknown): number | undefined {
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? number : undefined;
}

function parseSizeString(size: unknown): { width: number; height: number } | undefined {
  const sizeMatch = typeof size === 'string'
    ? size.match(/^\s*(\d+)\s*(?:x|\u00d7)\s*(\d+)\s*$/i)
    : null;
  if (!sizeMatch) return undefined;
  const sizeWidth = positiveNumber(sizeMatch[1]);
  const sizeHeight = positiveNumber(sizeMatch[2]);
  if (!sizeWidth || !sizeHeight) return undefined;
  return { width: sizeWidth, height: sizeHeight };
}

function parseImageRatio(input: any): number {
  const width = positiveNumber(input.width);
  const height = positiveNumber(input.height);
  if (width && height) return width / height;

  const aspectMatch = typeof input.aspectRatio === 'string'
    ? input.aspectRatio.match(/^\s*(\d+(?:\.\d+)?)\s*:\s*(\d+(?:\.\d+)?)\s*$/)
    : null;
  if (aspectMatch) {
    const ratioWidth = positiveNumber(aspectMatch[1]);
    const ratioHeight = positiveNumber(aspectMatch[2]);
    if (ratioWidth && ratioHeight) return ratioWidth / ratioHeight;
  }

  const fromSize = parseSizeString(input.size);
  if (fromSize) return fromSize.width / fromSize.height;
  return 1;
}

/**
 * Estimate display box for auto-root placement (x/y grid).
 * Prefer explicit size strings so multi-image spacing roughly matches final pixels.
 */
export function getAutoGeneratedImageSize(input: any): { width: number; height: number } {
  const width = positiveNumber(input.width);
  const height = positiveNumber(input.height);
  if (width && height) return { width, height };

  const fromSize = parseSizeString(input.size);
  if (fromSize) return fromSize;

  const ratio = parseImageRatio(input);
  if (width) return { width, height: Math.max(1, Math.round(width / ratio)) };
  if (height) return { width: Math.max(1, Math.round(height * ratio)), height };
  if (ratio >= 1) {
    return {
      width: AUTO_LAYOUT_MAX_EDGE,
      height: Math.max(1, Math.round(AUTO_LAYOUT_MAX_EDGE / ratio)),
    };
  }
  return {
    width: Math.max(1, Math.round(AUTO_LAYOUT_MAX_EDGE * ratio)),
    height: AUTO_LAYOUT_MAX_EDGE,
  };
}

/**
 * generate_image — creates an ImageGen node on the canvas and kicks off the
 * REAL image generation via AiService. Returns a taskId; the frontend reuses
 * its existing getTaskStatus polling to swap the placeholder for the result.
 */
export const generateImageTool: AgentTool = {
  name: 'generate_image',
  description:
    'Generate an image from a text prompt and place it on the canvas. Use for ' +
    'illustrations, photos, backgrounds, icons, concept art, and finished bitmap designs. ' +
    'For a final image, use a concise prompt that faithfully conveys the user intent. ' +
    'Prefer the user wording when sufficient and add only details the request genuinely requires.',
  parameters: {
    type: 'object',
    properties: {
      refId: { type: 'string', description: 'Optional stable ID for batching dependent tool calls in the same response.' },
      prompt: { type: 'string', description: 'Concise image request faithful to the user intent.' },
      model: { type: 'string', description: 'Optional image model id. Usually omit unless the user selected one.' },
      aspectRatio: { type: 'string', description: 'Optional aspect ratio such as 1:1, 16:9, 3:4, or a provider-supported custom ratio.' },
      size: { type: 'string', description: 'e.g. "1024x1024" (optional)' },
      quality: { type: 'string', description: 'Optional provider quality such as auto, low, medium, high, standard, hd, 1K, 2K.' },
      style: { type: 'string', description: 'optional style hint' },
      refImages: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Optional array of stable assetIds, canvas refIds, or absolute URLs to use as visual references. ' +
          'When exactly one canvas image is selected, omitting this field inherits that selection; pass [] explicitly only for a fresh generation unrelated to the selection.',
      },
      platform: { type: 'string', enum: ['amazon', 'taobao', 'jd'], description: 'Optional ecommerce platform tag for plan tracking.' },
      deliverable: { type: 'string', description: 'Optional deliverable role such as main, lifestyle, selling_point, or detail.' },
      x: { type: 'number', description: 'X position in pixels. Omit if the parentId points to an auto-layout container.' },
      y: { type: 'number', description: 'Y position in pixels. Omit if the parentId points to an auto-layout container.' },
      width: { type: 'number' },
      height: { type: 'number' },
      parentId: { type: 'string', description: 'Optional frame/group refId. Omit to place the generated image directly on the root canvas.' },
    },
    required: ['prompt'],
  },
  async execute(input: any, ctx: ToolContext): Promise<ToolResult> {
    const refId = resolveNewCanvasRefId(ctx, input.refId, 'img');
    const ecommerceSuiteMode = ctx.directImageRequest === undefined;
    if (ecommerceSuiteMode) assertPlannedEcommerceSourceReady(ctx);
    const plannedPlacement = ecommerceSuiteMode
      ? reservePlannedEcommercePlacement(input, ctx)
      : null;
    const canvasNodes = getCanvasNodeMap(ctx);
    const requestedParentId = plannedPlacement ? undefined : input.parentId;
    const parentId = plannedPlacement
      ? undefined
      : resolveCanvasContainerParentId(ctx, requestedParentId);
    const parentNode = parentId ? canvasNodes.get(parentId) : undefined;
    const parentFrame = parentNode?.type === 'frame' ? parentNode : undefined;
    const requestedWidth = plannedPlacement?.width ?? input.width ?? parentFrame?.width;
    const requestedHeight = plannedPlacement?.height ?? input.height ?? parentFrame?.height;
    const hasExplicitRootPosition =
      Number.isFinite(Number(input.x)) && Number.isFinite(Number(input.y));
    const shouldAutoArrange = Boolean(
      !plannedPlacement && !parentId && !hasExplicitRootPosition,
    );
    const autoSize = shouldAutoArrange
      ? getAutoGeneratedImageSize({
          ...input,
          width: requestedWidth,
          height: requestedHeight,
        })
      : undefined;
    const width = requestedWidth ?? autoSize?.width;
    const height = requestedHeight ?? autoSize?.height;
    const derivedAspectRatio =
      typeof requestedWidth === 'number' && requestedWidth > 0 &&
      typeof requestedHeight === 'number' && requestedHeight > 0
        ? getGenerationAspectRatio(requestedWidth, requestedHeight)
        : undefined;
    const aspectRatio = plannedPlacement
      ? derivedAspectRatio
      : input.aspectRatio ?? derivedAspectRatio;
    const autoPlacement = shouldAutoArrange
      ? reserveRootGridPlacement(ctx, width ?? 400, height ?? 400)
      : undefined;
    const x = plannedPlacement?.x ?? (parentId
      ? input.x ?? 0
      : hasExplicitRootPosition
        ? Number(input.x)
        : autoPlacement?.x);
    const y = plannedPlacement?.y ?? (parentId
      ? input.y ?? 0
      : hasExplicitRootPosition
        ? Number(input.y)
        : autoPlacement?.y);
    // Auto-arranged root images keep grid x/y but must NOT lock display size —
    // the frontend swaps in naturalWidth/naturalHeight when generation finishes.
    // Only ecommerce planned slots and frame-filled children preserve the box.
    const preserveLayout = Boolean(
      plannedPlacement ||
      (parentFrame && typeof width === 'number' && typeof height === 'number'),
    );
    const plannedSize = plannedPlacement
      ? getGptImageGenerationSize(plannedPlacement.width, plannedPlacement.height)
      : undefined;
    const size = input.size ?? plannedSize;
    const quality = input.quality ?? (plannedPlacement ? 'high' : undefined);
    const prompt = plannedPlacement
      ? buildEcommerceImagePrompt(
          input.prompt,
          plannedPlacement,
        )
      : input.prompt;
    const refImages = Array.isArray(input.refImages)
      ? input.refImages.filter((ref: unknown): ref is string => typeof ref === 'string')
      : [];
    const explicitlySetReferences = Object.prototype.hasOwnProperty.call(
      input,
      'refImages',
    );
    if (
      ctx.directImageRequest === true &&
      !explicitlySetReferences &&
      ctx.defaultImageReferenceIds?.length === 1 &&
      !refImages.includes(ctx.defaultImageReferenceIds[0])
    ) {
      refImages.unshift(ctx.defaultImageReferenceIds[0]);
    }
    if (plannedPlacement?.sourceAssetId) {
      const orderedSources = [
        plannedPlacement.sourceAssetId,
        plannedPlacement.preferredSourceRefId,
      ].filter((ref): ref is string => Boolean(ref));
      for (const source of orderedSources) {
        const index = refImages.indexOf(source);
        if (index >= 0) refImages.splice(index, 1);
      }
      // Keep the original first as the identity source of truth. A prepared
      // upscale/cutout is a supplemental detail aid, not permission to redesign.
      refImages.unshift(...orderedSources);
    }

    if (plannedPlacement) {
      Object.assign(input, {
        platform: plannedPlacement.platform,
        deliverable: plannedPlacement.deliverable,
        x,
        y,
        width,
        height,
        aspectRatio,
        size,
        quality,
        refImages,
      });
      delete input.parentId;
    }
    const base64Images = await resolveReferencesToBase64(refImages, ctx);
    const referenceAssetId = plannedPlacement?.sourceAssetId ?? refImages.find(
      (ref: string) => ctx.assets?.some((asset) => asset.id === ref),
    );

    const nodeSpec = {
      refId,
      type: 'image_gen' as const,
      parentId,
      prompt,
      model: input.model,
      aspectRatio,
      size,
      quality,
      x,
      y,
      width,
      height,
      preserveLayout,
      images: base64Images,
      platform: plannedPlacement?.platform ?? input.platform,
      deliverable: plannedPlacement?.deliverable ?? input.deliverable,
    };

    // 1. tell the canvas to create an ImageGen placeholder node
    ctx.sink.canvas({ op: 'add_node', node: nodeSpec });

    // 2. kick off the REAL generation through the existing AiService
    const billed = await startBilledAgentTask(
      ctx,
      'image_generation',
      { prompt, model: input.model, quality, size, aspectRatio, referenceCount: base64Images.length },
      (billingContext) => ctx.ai.generateImageFromJson(
        {
          prompt,
          model: input.model,
          style: input.style,
          size,
          aspectRatio,
          quality,
          images: base64Images,
        },
        ctx.origin,
        billingContext,
      ),
    );
    const res = billed.result;

    upsertCanvasNode(ctx, refId, {
      ...nodeSpec,
      taskId: (res as any).taskId,
      status: 'generating',
    });


    // 3. hand the taskId to the frontend so it polls via its existing pipeline
    ctx.sink.canvas({
      op: 'generation_started',
      refId,
      kind: 'image',
      taskId: (res as any).taskId,
    });

    const resolvedModel =
      (typeof (res as any)?.model === 'string' && (res as any).model) ||
      (typeof input.model === 'string' && input.model.trim()) ||
      undefined;

    return {
      output: {
        refId,
        taskId: (res as any).taskId,
        status: (res as any).status,
        model: resolvedModel,
        parentId,
        x,
        y,
        width,
        height,
        aspectRatio,
        size,
        quality,
        platform: plannedPlacement?.platform ?? input.platform,
        deliverable: plannedPlacement?.deliverable ?? input.deliverable,
        referenceAssetId,
        billingOperationId: billed.billingOperationId,
        note: 'ImageGen node created and generation started. The canvas will poll for the result.',
      },
    };
  },
};

/**
 * generate_video — same flow as generate_image but via generateVideoFromJson.
 */
export const generateVideoTool: AgentTool = {
  name: 'generate_video',
  description:
    'Generate a short video from a text prompt (optionally from a reference ' +
    'image) and place it on the canvas. Use for animated banners, motion ' +
    'backgrounds, short clips.',
  parameters: {
    type: 'object',
    properties: {
      refId: { type: 'string', description: 'Optional stable ID for batching dependent tool calls in the same response.' },
      prompt: { type: 'string' },
      model: { type: 'string', description: 'Optional video model id. Usually omit unless the user selected one.' },
      aspectRatio: { type: 'string', enum: ['16:9', '9:16', '1:1'] },
      size: { type: 'string' },
      seconds: { type: 'string', description: 'clip length, e.g. "5"' },
      refImages: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional array containing the refId of the reference image on the canvas to use as input reference for video generation.',
      },
      x: { type: 'number' },
      y: { type: 'number' },
      parentId: { type: 'string', description: 'Optional frame/group refId. Omit to place the generated video directly on the root canvas.' },
    },
    required: ['prompt'],
  },
  async execute(input: any, ctx: ToolContext): Promise<ToolResult> {
    const refId = resolveNewCanvasRefId(ctx, input.refId, 'vid');
    const parentId = resolveCanvasContainerParentId(ctx, input.parentId);
    const base64Images = await resolveReferencesToBase64(input.refImages, ctx);
    const inputReference = base64Images[0] || '';
    const preparedRequest = await ctx.ai.prepareVideoGenerationRequest({
      prompt: input.prompt,
      model: input.model,
      size: input.size,
      seconds: input.seconds,
      input_reference: inputReference,
    });

    const nodeSpec = {
      refId,
      type: 'video_gen' as const,
      parentId,
      prompt: preparedRequest.prompt,
      model: preparedRequest.model,
      aspectRatio: input.aspectRatio,
      size: preparedRequest.size,
      seconds: preparedRequest.seconds,
      x: input.x,
      y: input.y,
      inputReference: preparedRequest.input_reference,
    };

    ctx.sink.canvas({ op: 'add_node', node: nodeSpec });

    const billed = await startBilledAgentTask(
      ctx,
      'video_generation',
      { ...preparedRequest, hasReference: Boolean(preparedRequest.input_reference) },
      (billingContext) => ctx.ai.generateVideoFromJson(
        preparedRequest,
        ctx.origin,
        billingContext,
      ),
    );
    const res = billed.result;

    upsertCanvasNode(ctx, refId, {
      ...nodeSpec,
      taskId: (res as any).taskId,
      status: 'generating',
    });


    ctx.sink.canvas({
      op: 'generation_started',
      refId,
      kind: 'video',
      taskId: (res as any).taskId,
    });

    return {
      output: {
        refId,
        taskId: (res as any).taskId,
        status: (res as any).status,
        billingOperationId: billed.billingOperationId,
        note: 'VideoGen node created and generation started.',
      },
    };
  },
};
