import type { AgentTool, ToolContext, ToolResult } from '../tool.interface';
import { startBilledAgentTask } from '../../billing/billing-task';
import {
  getCanvasNodeMap,
  reserveRootGridPlacement,
  resolveCanvasContainerParentId,
  resolveNewCanvasRefId,
  upsertCanvasNode,
} from '../canvas-state';
import { applyFinalImageRequestPolicy } from '../image-request-policy';
import { IMAGE_REQUEST_POLICY_ERROR } from '../image-suite-plan';
import { resolveReferencesToBase64 } from './image-reference';

/**
 * Grid reservation / placeholder estimate only.
 * Final canvas display uses natural image pixels unless preserveLayout is set
 * (for example, images constrained to a parent frame).
 * Prefer a larger placeholder so 1K/2K results don't briefly appear as a tiny 400 box.
 */
const AUTO_LAYOUT_MAX_EDGE = 1024;

function positiveNumber(value: unknown): number | undefined {
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? number : undefined;
}

function parseSizeString(size: unknown): { width: number; height: number } | undefined {
  const sizeMatch = typeof size === 'string'
    ? size.match(/^\s*(\d+)\s*(?:x|\u00d7)\s*(\d+)\s*$/i)
    : null;
  if (!sizeMatch) return undefined;
  const sizeWidth = positiveNumber(sizeMatch[1]);
  const sizeHeight = positiveNumber(sizeMatch[2]);
  if (!sizeWidth || !sizeHeight) return undefined;
  return { width: sizeWidth, height: sizeHeight };
}

function parseImageRatio(input: any): number {
  const width = positiveNumber(input.width);
  const height = positiveNumber(input.height);
  if (width && height) return width / height;

  const aspectMatch = typeof input.aspectRatio === 'string'
    ? input.aspectRatio.match(/^\s*(\d+(?:\.\d+)?)\s*:\s*(\d+(?:\.\d+)?)\s*$/)
    : null;
  if (aspectMatch) {
    const ratioWidth = positiveNumber(aspectMatch[1]);
    const ratioHeight = positiveNumber(aspectMatch[2]);
    if (ratioWidth && ratioHeight) return ratioWidth / ratioHeight;
  }

  const fromSize = parseSizeString(input.size);
  if (fromSize) return fromSize.width / fromSize.height;
  return 1;
}

/**
 * Estimate display box for auto-root placement (x/y grid).
 * Prefer explicit size strings so multi-image spacing roughly matches final pixels.
 */
export function getAutoGeneratedImageSize(input: any): { width: number; height: number } {
  const width = positiveNumber(input.width);
  const height = positiveNumber(input.height);
  if (width && height) return { width, height };

  const fromSize = parseSizeString(input.size);
  if (fromSize) return fromSize;

  const ratio = parseImageRatio(input);
  if (width) return { width, height: Math.max(1, Math.round(width / ratio)) };
  if (height) return { width: Math.max(1, Math.round(height * ratio)), height };
  if (ratio >= 1) {
    return {
      width: AUTO_LAYOUT_MAX_EDGE,
      height: Math.max(1, Math.round(AUTO_LAYOUT_MAX_EDGE / ratio)),
    };
  }
  return {
    width: Math.max(1, Math.round(AUTO_LAYOUT_MAX_EDGE * ratio)),
    height: AUTO_LAYOUT_MAX_EDGE,
  };
}

const GENERATION_RATIOS = [
  ['1:1', 1],
  ['1:4', 1 / 4],
  ['1:8', 1 / 8],
  ['2:3', 2 / 3],
  ['3:2', 3 / 2],
  ['3:4', 3 / 4],
  ['4:1', 4],
  ['4:3', 4 / 3],
  ['4:5', 4 / 5],
  ['5:4', 5 / 4],
  ['8:1', 8],
  ['9:16', 9 / 16],
  ['16:9', 16 / 9],
  ['21:9', 21 / 9],
] as const;

export function getGenerationAspectRatio(width: number, height: number): string {
  const target = width / height;
  return GENERATION_RATIOS.reduce((best, candidate) =>
    Math.abs(Math.log(candidate[1] / target)) < Math.abs(Math.log(best[1] / target))
      ? candidate
      : best,
  )[0];
}

/**
 * generate_image — creates an ImageGen node on the canvas and kicks off the
 * REAL image generation via AiService. Returns a taskId; the frontend reuses
 * its existing getTaskStatus polling to swap the placeholder for the result.
 */
export const generateImageTool: AgentTool = {
  name: 'generate_image',
  description:
    'Generate a finished bitmap and place it on the canvas. Unless the user explicitly asks to optimize or rewrite the prompt, remove only a leading request wrapper such as 请/帮我/please/help me and set prompt to the remaining user task exactly as written. ' +
    'For a platform 套图/suite, make one structured call per required deliverable. Set platform and deliverable, and put only exact relevant user wording in userConstraints; the server compiles the final prompt. ' +
    'Do not translate, expand, professionalize, summarize, or append platform/design instructions. Pass attached or selected images in refImages instead of describing them in prompt.',
  parameters: {
    type: 'object',
    properties: {
      refId: { type: 'string', description: 'Optional stable ID for batching dependent tool calls in the same response.' },
      prompt: {
        type: 'string',
        description:
          'Image-model prompt. For an ordinary request, remove only a leading conversational request wrapper and copy the remaining user task exactly. In normal platform-suite mode this field is only a tool-call placeholder: the server ignores its creative wording and deterministically compiles the final prompt from deliverable plus verified userConstraints. Only an explicit prompt-optimization request permits creative expansion.',
      },
      platform: {
        type: 'string',
        description:
          'For a platform suite, the marketplace id such as amazon, taobao, jd, shopee, or temu. Omit for an ordinary single image.',
      },
      deliverable: {
        type: 'string',
        description:
          'For a platform suite, one short deliverable role id or artifact name, such as main, a_plus, 详情页, or 店铺横幅图. Never place visual direction here.',
      },
      userConstraints: {
        type: 'array',
        items: { type: 'string' },
        description:
          'For a platform suite, only relevant constraint snippets copied exactly from the current user message. Invented snippets are discarded before prompt compilation.',
      },
      model: { type: 'string', description: 'Optional image model id. Usually omit unless the user selected one.' },
      aspectRatio: { type: 'string', description: 'Optional aspect ratio such as 1:1, 16:9, 3:4, or a provider-supported custom ratio.' },
      size: {
        type: 'string',
        description:
          'Optional provider-supported pixel size in WIDTHxHEIGHT form. Omit when aspect ratio and provider defaults are sufficient.',
      },
      quality: { type: 'string', description: 'Optional provider quality such as auto, low, medium, high, standard, hd, 1K, 2K.' },
      style: {
        type: 'string',
        description: 'Optional provider style control. Use only when the user explicitly requested prompt optimization.',
      },
      seriesRole: {
        type: 'string',
        description:
          'Optional semantic role for this image in a multi-image suite (for example main, lifestyle, visible_detail, detail_overview). Use a distinct role per deliverable.',
      },
      repairOf: {
        type: 'string',
        description:
          'For the single bounded automatic regeneration after visual verification fails, set this to the failed image refId. Omit for an initial or genuinely distinct deliverable.',
      },
      refImages: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Optional array of stable assetIds, canvas refIds, or absolute URLs to use as visual references. ' +
          'When exactly one canvas image is selected, omitting this field inherits that selection; pass [] explicitly only for a fresh generation unrelated to the selection.',
      },
      x: { type: 'number', description: 'X position in pixels. Omit if the parentId points to an auto-layout container.' },
      y: { type: 'number', description: 'Y position in pixels. Omit if the parentId points to an auto-layout container.' },
      width: { type: 'number' },
      height: { type: 'number' },
      parentId: { type: 'string', description: 'Optional frame/group refId. Omit to place the generated image directly on the root canvas.' },
    },
    required: ['prompt'],
  },
  async execute(input: any, ctx: ToolContext): Promise<ToolResult> {
    if (ctx.directImageRequest === true) {
      input = applyFinalImageRequestPolicy('generate_image', input, ctx.userInput);
    }
    if (typeof input?.[IMAGE_REQUEST_POLICY_ERROR] === 'string') {
      throw new Error(input[IMAGE_REQUEST_POLICY_ERROR]);
    }
    const refId = resolveNewCanvasRefId(ctx, input.refId, 'img');
    const canvasNodes = getCanvasNodeMap(ctx);
    const parentId = resolveCanvasContainerParentId(ctx, input.parentId);
    const parentNode = parentId ? canvasNodes.get(parentId) : undefined;
    const parentFrame = parentNode?.type === 'frame' ? parentNode : undefined;
    const requestedWidth = input.width ?? parentFrame?.width;
    const requestedHeight = input.height ?? parentFrame?.height;
    const hasExplicitRootPosition =
      Number.isFinite(Number(input.x)) && Number.isFinite(Number(input.y));
    const shouldAutoArrange = Boolean(
      !parentId && !hasExplicitRootPosition,
    );
    const autoSize = shouldAutoArrange
      ? getAutoGeneratedImageSize({
          ...input,
          width: requestedWidth,
          height: requestedHeight,
        })
      : undefined;
    const width = requestedWidth ?? autoSize?.width;
    const height = requestedHeight ?? autoSize?.height;
    const derivedAspectRatio = ctx.directImageRequest === true
      ? undefined
      :
      typeof requestedWidth === 'number' && requestedWidth > 0 &&
      typeof requestedHeight === 'number' && requestedHeight > 0
        ? getGenerationAspectRatio(requestedWidth, requestedHeight)
        : undefined;
    const aspectRatio = input.aspectRatio ?? derivedAspectRatio;
    const autoPlacement = shouldAutoArrange
      ? reserveRootGridPlacement(ctx, width ?? 400, height ?? 400)
      : undefined;
    const x = parentId
      ? input.x ?? 0
      : hasExplicitRootPosition
        ? Number(input.x)
        : autoPlacement?.x;
    const y = parentId
      ? input.y ?? 0
      : hasExplicitRootPosition
        ? Number(input.y)
        : autoPlacement?.y;
    // Auto-arranged root images keep grid x/y but must NOT lock display size —
    // the frontend swaps in naturalWidth/naturalHeight when generation finishes.
    // Only frame-filled children preserve the box.
    const preserveLayout = Boolean(
      parentFrame && typeof width === 'number' && typeof height === 'number',
    );
    const size = input.size;
    const quality = input.quality;
    const prompt = input.prompt;
    const refImages = Array.isArray(input.refImages)
      ? input.refImages.filter((ref: unknown): ref is string => typeof ref === 'string')
      : [];
    const explicitlySetReferences = Object.prototype.hasOwnProperty.call(
      input,
      'refImages',
    );
    if (
      ctx.directImageRequest === true &&
      !explicitlySetReferences &&
      ctx.defaultImageReferenceIds?.length === 1 &&
      !refImages.includes(ctx.defaultImageReferenceIds[0])
    ) {
      refImages.unshift(ctx.defaultImageReferenceIds[0]);
    }
    const base64Images = await resolveReferencesToBase64(refImages, ctx);
    const referenceAssetId = refImages.find(
      (ref: string) => ctx.assets?.some((asset) => asset.id === ref),
    );

    const nodeSpec = {
      refId,
      type: 'image_gen' as const,
      parentId,
      prompt,
      model: input.model,
      aspectRatio,
      size,
      quality,
      platform: input.platform,
      deliverable: input.deliverable,
      userConstraints: input.userConstraints,
      seriesRole: input.seriesRole,
      repairOf: input.repairOf,
      x,
      y,
      width,
      height,
      preserveLayout,
      images: base64Images,
    };

    // 1. tell the canvas to create an ImageGen placeholder node
    ctx.sink.canvas({ op: 'add_node', node: nodeSpec });

    // 2. kick off the REAL generation through the existing AiService
    const billed = await startBilledAgentTask(
      ctx,
      'image_generation',
      { prompt, model: input.model, quality, size, aspectRatio, referenceCount: base64Images.length },
      (billingContext) => ctx.ai.generateImageFromJson(
        {
          prompt,
          model: input.model,
          style: input.style,
          size,
          aspectRatio,
          quality,
          images: base64Images,
        },
        ctx.origin,
        billingContext,
      ),
    );
    const res = billed.result;

    upsertCanvasNode(ctx, refId, {
      ...nodeSpec,
      taskId: (res as any).taskId,
      status: 'generating',
    });


    // 3. hand the taskId to the frontend so it polls via its existing pipeline
    ctx.sink.canvas({
      op: 'generation_started',
      refId,
      kind: 'image',
      taskId: (res as any).taskId,
    });

    const resolvedModel =
      (typeof (res as any)?.model === 'string' && (res as any).model) ||
      (typeof input.model === 'string' && input.model.trim()) ||
      undefined;

    return {
      output: {
        refId,
        taskId: (res as any).taskId,
        status: (res as any).status,
        model: resolvedModel,
        parentId,
        x,
        y,
        width,
        height,
        aspectRatio,
        size,
        quality,
        platform: input.platform,
        deliverable: input.deliverable,
        userConstraints: input.userConstraints,
        seriesRole: input.seriesRole,
        repairOf: input.repairOf,
        referenceAssetId,
        billingOperationId: billed.billingOperationId,
        note: 'ImageGen node created and generation started. The canvas will poll for the result.',
      },
    };
  },
};

/**
 * generate_video — same flow as generate_image but via generateVideoFromJson.
 */
export const generateVideoTool: AgentTool = {
  name: 'generate_video',
  description:
    'Generate a short video from a text prompt (optionally from a reference ' +
    'image) and place it on the canvas. Use for animated banners, motion ' +
    'backgrounds, short clips.',
  parameters: {
    type: 'object',
    properties: {
      refId: { type: 'string', description: 'Optional stable ID for batching dependent tool calls in the same response.' },
      prompt: { type: 'string' },
      model: { type: 'string', description: 'Optional video model id. Usually omit unless the user selected one.' },
      aspectRatio: { type: 'string', enum: ['16:9', '9:16', '1:1'] },
      size: { type: 'string' },
      seconds: { type: 'string', description: 'clip length, e.g. "5"' },
      refImages: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional array containing the refId of the reference image on the canvas to use as input reference for video generation.',
      },
      x: { type: 'number' },
      y: { type: 'number' },
      parentId: { type: 'string', description: 'Optional frame/group refId. Omit to place the generated video directly on the root canvas.' },
    },
    required: ['prompt'],
  },
  async execute(input: any, ctx: ToolContext): Promise<ToolResult> {
    const refId = resolveNewCanvasRefId(ctx, input.refId, 'vid');
    const parentId = resolveCanvasContainerParentId(ctx, input.parentId);
    const base64Images = await resolveReferencesToBase64(input.refImages, ctx);
    const inputReference = base64Images[0] || '';
    const preparedRequest = await ctx.ai.prepareVideoGenerationRequest({
      prompt: input.prompt,
      model: input.model,
      size: input.size,
      seconds: input.seconds,
      input_reference: inputReference,
    });

    const nodeSpec = {
      refId,
      type: 'video_gen' as const,
      parentId,
      prompt: preparedRequest.prompt,
      model: preparedRequest.model,
      aspectRatio: input.aspectRatio,
      size: preparedRequest.size,
      seconds: preparedRequest.seconds,
      x: input.x,
      y: input.y,
      inputReference: preparedRequest.input_reference,
    };

    ctx.sink.canvas({ op: 'add_node', node: nodeSpec });

    const billed = await startBilledAgentTask(
      ctx,
      'video_generation',
      { ...preparedRequest, hasReference: Boolean(preparedRequest.input_reference) },
      (billingContext) => ctx.ai.generateVideoFromJson(
        preparedRequest,
        ctx.origin,
        billingContext,
      ),
    );
    const res = billed.result;

    upsertCanvasNode(ctx, refId, {
      ...nodeSpec,
      taskId: (res as any).taskId,
      status: 'generating',
    });


    ctx.sink.canvas({
      op: 'generation_started',
      refId,
      kind: 'video',
      taskId: (res as any).taskId,
    });

    return {
      output: {
        refId,
        taskId: (res as any).taskId,
        status: (res as any).status,
        billingOperationId: billed.billingOperationId,
        note: 'VideoGen node created and generation started.',
      },
    };
  },
};
