import { createApp } from 'vue';
import 'normalize.css';
import 'virtual:uno.css';
import 'primeicons/primeicons.css';
import '@incremark/theme/incremark.css';
import '@/styles/tokens.css';
import '@/assets/iconfont/iconfont.css';

import App from './App.vue';
import PrimeVue from 'primevue/config';
import { NoirPreset } from '@/themes/app-theme';
import router from '@/router';
import { ConfirmationService } from 'primevue';
import ToastService from 'primevue/toastservice';
import { initTheme } from '@/composables/useTheme';

// Apply saved / OS theme before mount to avoid a flash of the wrong theme.
initTheme();

const app = createApp(App);
app.use(PrimeVue, {
  theme: {
    preset: NoirPreset,
    options: {
      darkModeSelector: '.p-dark',
    },
  },
  locale: {
    primevue: {
      day: '日',
      startsWith: '前缀',
      contains: '包含',
      notContains: '不包含',
      endsWith: '后缀',
      equals: '等于',
      notEquals: '不等于',
      noFilter: '没有过滤',
      lt: '小于',
      lte: '小于等于',
      gt: '大于',
      gte: '大于等于',
      dateIs: '日期为',
      dateIsNot: '日期非',
      dateBefore: '日期前',
      dateAfter: '日期后',
      clear: '清除',
      apply: '应用',
      matchAll: '匹配所有',
      matchAny: '匹配任意',
      addRule: '添加规则',
      removeRule: '删除规则',
      accept: '是',
      reject: '否',
      choose: '选择',
      upload: '上传',
      cancel: '取消',
      completed: '完成',
      pending: '处理中',
      fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
      dayNames: [
        '星期日',
        '星期一',
        '星期二',
        '星期三',
        '星期四',
        '星期五',
        '星期六',
      ],
      dayNamesShort: ['日', '一', '二', '三', '四', '五', '六'],
      dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
      monthNames: [
        '1 月',
        '2 月',
        '3 月',
        '4 月',
        '5 月',
        '6 月',
        '7 月',
        '8 月',
        '9 月',
        '10 月',
        '11 月',
        '12 月',
      ],
      monthNamesShort: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
      ],
      chooseYear: '选择年份',
      chooseMonth: '选择月份',
      chooseDate: '选择日期',
      prevDecade: '前十年',
      nextDecade: '后十年',
      prevYear: '上一年',
      nextYear: '下一年',
      prevMonth: '上一个月',
      nextMonth: '下一个月',
      prevHour: '上一小时',
      nextHour: '下一小时',
      prevMinute: '上一分钟',
      nextMinute: '下一分钟',
      prevSecond: '上一秒',
      nextSecond: '下一秒',
      am: '上午',
      pm: '下午',
      today: '今天',
      weekHeader: '星期',
      firstDayOfWeek: 0,
      showMonthAfterYear: true,
      dateFormat: 'mm/dd/yy',
      weak: '弱',
      medium: '中',
      strong: '强',
      passwordPrompt: '输入密码',
      emptyFilterMessage: '没有结果',
      searchMessage: '找到 {0} 个结果',
      selectionMessage: '选中 {0} 个对象',
      emptySelectionMessage: '没有选中对象',
      emptySearchMessage: '没有找到结果',
      fileChosenMessage: '{0} 个文件',
      noFileChosenMessage: '未选择文件',
      emptyMessage: '没有选项',
      aria: {
        trueLabel: '真',
        falseLabel: '假',
        nullLabel: '未选择',
        star: '1 星',
        stars: '{star} 星',
        selectAll: '选中所有',
        unselectAll: '取消所有有选中',
        close: '关闭',
        previous: '上一个',
        next: '下一个',
        navigation: '导航',
        scrollTop: '滚动到顶部',
        moveTop: '移动到顶部',
        moveUp: '向上移动',
        moveDown: '向下移动',
        moveBottom: '移动到底部',
        moveToTarget: '移动到目标',
        moveToSource: '移动到来源',
        moveAllToTarget: '全部移动到目标',
        moveAllToSource: '全部移动到来源',
        pageLabel: '页 {page}',
        firstPageLabel: '第一页',
        lastPageLabel: '最后一页',
        nextPageLabel: '下一页',
        prevPageLabel: '上一页',
        rowsPerPageLabel: '行每页',
        jumpToPageDropdownLabel: '前往下拉列表',
        jumpToPageInputLabel: '前往输入框',
        selectRow: '已选中行',
        unselectRow: '未选中行',
        expandRow: '已展开行',
        collapseRow: '未展开行',
        showFilterMenu: '显示过滤菜单',
        hideFilterMenu: '隐藏过滤菜单',
        filterOperator: '过滤操作',
        filterConstraint: '过滤条件',
        editRow: '编辑行',
        saveEdit: '保存修改',
        cancelEdit: '放弃修改',
        listView: '列表形式',
        gridView: '表格形式',
        slide: '幻灯片',
        slideNumber: '{slideNumber}',
        zoomImage: '缩放图片',
        zoomIn: '放大',
        zoomOut: '缩小',
        rotateRight: '向右旋转',
        rotateLeft: '向左旋转',
        listLabel: '选项列表',
      },
    },
  },
});
app.use(router);
app.use(ConfirmationService);
app.use(ToastService);
app.mount('#app');
